# Generated by Django 2.1.2 on 2018-10-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djadesh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimages',
            name='img',
            field=models.ImageField(null=True, upload_to='items'),
        ),
    ]
