# Generated by Django 2.1.2 on 2018-10-19 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djadesh', '0002_itemimages_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemproperty',
            name='item',
        ),
        migrations.AddField(
            model_name='itemproperty',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djadesh.Item'),
        ),
    ]
