# Generated by Django 2.1.2 on 2018-10-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djadesh', '0003_auto_20181019_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemproperty',
            name='item',
        ),
        migrations.AddField(
            model_name='itemproperty',
            name='items',
            field=models.ManyToManyField(related_name='properties', to='djadesh.Item'),
        ),
    ]
