# Generated by Django 2.1.2 on 2018-10-19 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djadesh', '0004_auto_20181019_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemproperty',
            name='items',
        ),
        migrations.AddField(
            model_name='itemproperty',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djadesh.Item'),
        ),
    ]
