# Generated by Django 2.1.2 on 2018-10-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djadesh', '0005_auto_20181019_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemproperty',
            name='item',
        ),
        migrations.AddField(
            model_name='itemproperty',
            name='items',
            field=models.ManyToManyField(to='djadesh.Item'),
        ),
    ]
