# Generated by Django 2.1.2 on 2018-10-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djadesh', '0006_auto_20181024_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemproperty',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='properties',
            field=models.ManyToManyField(to='djadesh.ItemProperty'),
        ),
    ]
