# Generated by Django 2.1.2 on 2018-10-24 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djadesh', '0007_auto_20181024_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='properties',
        ),
        migrations.AddField(
            model_name='itemproperty',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djadesh.Item'),
        ),
    ]
