# Generated by Django 2.1.2 on 2018-10-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djadesh', '0008_auto_20181024_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemproperty',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
