# Generated by Django 2.1.2 on 2018-10-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djadesh', '0009_itemproperty_is_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
