# Generated by Django 2.1.2 on 2018-10-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djadesh', '0010_auto_20181026_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
