# Generated by Django 2.1.2 on 2018-10-28 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djadesh', '0011_auto_20181026_1319'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemImages',
            new_name='ItemImage',
        ),
    ]
