# Generated by Django 2.1.2 on 2018-10-28 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djadesh', '0013_auto_20181028_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemproperty',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', related_query_name='property', to='djadesh.Item'),
        ),
    ]
